In [26]:
import pandas as pd

In [45]:
import numpy as np

In [25]:
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(url, encoding = 'latin1', sep = ';')
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [24]:
df.tail()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37994,159,6,2026,2026m06,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,0.0,0.0,18,1,0,0,0,0,158,2
37995,165,6,2026,2026m06,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,49,2,1,0,0,0,202,2
37996,166,6,2026,2026m06,33,5,Angra dos Reis,3300100,Interior,1,...,14.0,0.0,81,8,0,0,0,0,641,2
37997,167,6,2026,2026m06,43,5,Paraty,3303807,Interior,1,...,4.0,0.0,14,1,1,0,0,0,198,2
37998,168,6,2026,2026m06,28,5,Rio Claro,3304409,Interior,0,...,0.0,0.0,4,0,0,0,0,0,32,2

In [23]:
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37999 entries, 0 to 37998
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37999 non-null  int64
 1   mes                         37999 non-null  int64
 2   ano                         37999 non-null  int64
 3   mes_ano                     37999 non-null  str
 4   aisp                        37999 non-null  int64
 5   risp                        37999 non-null  int64
 6   munic                       37999 non-null  str
 7   mcirc                       37999 non-null  int64
 8   regiao                      37999 non-null  str
 9   hom_doloso                  37999 non-null  int64
 10  lesao_corp_morte            37999 non-null  int64
 11  latrocinio                  37999 non-null  int64
 12  cvli                        37999 non-null  int64
 13  hom_por_interv_policial     37999 non-null  int64
 14  feminicidio                 2877 non-null   float64
 15  letalidade_violenta         37999 non-null  int64
 16  tentat_hom                  37999 non-null  int64
 17  tentativa_feminicidio       2877 non-null   float64
 18  lesao_corp_dolosa           37999 non-null  int64
 19  estupro                     37999 non-null  int64
 20  hom_culposo                 37999 non-null  int64
 21  lesao_corp_culposa          37999 non-null  int64
 22  roubo_transeunte            37999 non-null  int64
 23  roubo_celular               37999 non-null  int64
 24  roubo_em_coletivo           37999 non-null  int64
 25  roubo_rua                   37999 non-null  int64
 26  roubo_veiculo               37999 non-null  int64
 27  roubo_carga                 37999 non-null  int64
 28  roubo_comercio              37999 non-null  int64
 29  roubo_residencia            37999 non-null  int64
 30  roubo_banco                 37999 non-null  int64
 31  roubo_cx_eletronico         37980 non-null  float64
 32  roubo_conducao_saque        37999 non-null  int64
 33  roubo_apos_saque            37999 non-null  int64
 34  roubo_bicicleta             20610 non-null  float64
 35  outros_roubos               37999 non-null  int64
 36  total_roubos                37999 non-null  int64
 37  furto_veiculos              37999 non-null  int64
 38  furto_transeunte            37999 non-null  int64
 39  furto_coletivo              37999 non-null  int64
 40  furto_celular               37999 non-null  int64
 41  furto_bicicleta             20610 non-null  float64
 42  outros_furtos               37999 non-null  int64
 43  total_furtos                37999 non-null  int64
 44  sequestro                   37999 non-null  int64
 45  extorsao                    37999 non-null  int64
 46  sequestro_relampago         37999 non-null  int64
 47  estelionato                 37999 non-null  int64
 48  apreensao_drogas            37999 non-null  int64
 49  posse_drogas                33353 non-null  float64
 50  trafico_drogas              33353 non-null  float64
 51  apreensao_drogas_sem_autor  33353 non-null  float64
 52  recuperacao_veiculos        37999 non-null  int64
 53  apf                         33353 non-null  float64
 54  aaapai                      33353 non-null  float64
 55  cmp                         33353 non-null  float64
 56  cmba                        33353 non-null  float64
 57  ameaca                      37999 non-null  int64
 58  pessoas_desaparecidas       37999 non-null  int64
 59  encontro_cadaver            37999 non-null  int64
 60  encontro_ossada             37999 non-null  int64
 61  pol_militares_mortos_serv   37999 non-null  int64
 62  pol_civis_mortos_serv       37999 non-null  int64
 63  registro_ocorrencias        37999 non-null  int64
 64  fase                        37999 non-null  int64
dtypes: float64(12), int64(50), str(3)
memory usage: 18.8 MB

In [21]:
df.describe()

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000,3.799900e+04,37999.000000,37999.000000,37999.000000,37999.000000,...,33353.000000,33353.000000,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000,37999.000000
mean,81.724887,6.437485,2014.401642,20.158952,3.869918,3.791066e+06,2.901155,0.028264,0.094476,3.023895,...,8.724582,0.646569,41.445959,3.238664,0.359509,0.022816,0.013211,0.002211,447.112792,2.989184
std,48.320882,3.451510,6.750784,11.353647,2.011363,1.739697e+06,4.304049,0.180037,0.364154,4.418595,...,14.692666,1.640221,39.520032,4.170925,0.983036,0.180298,0.129919,0.049156,401.757025,0.103438
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2009.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,372.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,668.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [20]:
df_furto_cel_dp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp = df_furto_cel_dp.sort_values(by='furto_celular',ascending = False)
df_furto_cel_dp

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
..    ...            ...
87    104             73
77     92             65
114   138             56
131   157             55
129   155             47

[138 rows x 2 columns]

## usando o inplace True

In [19]:
df_furto_cel_dp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp.sort_values(by='furto_celular',ascending = False, inplace = True)
df_furto_cel_dp

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
..    ...            ...
87    104             73
77     92             65
114   138             56
131   157             55
129   155             47

[138 rows x 2 columns]

In [18]:
df_apreensao_menor_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_apreensao_menor_dp = df_apreensao_menor_dp.sort_values(by= 'aaapai',ascending = False)
df_apreensao_menor_dp

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

## Formula do Agrupamento

In [16]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp = df_roubo_veiculo_dp.sort_values(by = 'roubo_veiculo',ascending = False)
df_roubo_veiculo_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]

## Filtragem com .loc e query()

In [29]:
df_capital = df.loc[df['munic'] == 'Rio de Janeiro']
df_capital

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37898,40,6,2026,2026m06,9,2,Rio de Janeiro,3304557,Capital,3,...,8.0,3.0,38,1,0,0,0,0,617,2
37899,41,6,2026,2026m06,18,2,Rio de Janeiro,3304557,Capital,1,...,9.0,3.0,22,5,0,0,0,0,814,2
37900,42,6,2026,2026m06,31,2,Rio de Janeiro,3304557,Capital,4,...,12.0,2.0,99,7,1,0,0,0,1319,2
37901,43,6,2026,2026m06,27,2,Rio de Janeiro,3304557,Capital,0,...,6.0,1.0,96,7,0,0,0,0,720,2
37902,44,6,2026,2026m06,3,1,Rio de Janeiro,3304557,Capital,0,...,15.0,3.0,46,6,0,0,0,0,790,2

In [34]:
df_capital = df.query("munic == 'Rio de Janeiro'")
df_capital

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37898,40,6,2026,2026m06,9,2,Rio de Janeiro,3304557,Capital,3,...,8.0,3.0,38,1,0,0,0,0,617,2
37899,41,6,2026,2026m06,18,2,Rio de Janeiro,3304557,Capital,1,...,9.0,3.0,22,5,0,0,0,0,814,2
37900,42,6,2026,2026m06,31,2,Rio de Janeiro,3304557,Capital,4,...,12.0,2.0,99,7,1,0,0,0,1319,2
37901,43,6,2026,2026m06,27,2,Rio de Janeiro,3304557,Capital,0,...,6.0,1.0,96,7,0,0,0,0,720,2
37902,44,6,2026,2026m06,3,1,Rio de Janeiro,3304557,Capital,0,...,15.0,3.0,46,6,0,0,0,0,790,2

## Filtragem + Agrupamento

In [40]:
df_bel = df.loc[df['munic'] == 'Belford Roxo']
df_bel

df_furto_cel_bel_dp = df_bel.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_furto_cel_bel_dp.sort_values(by='roubo_veiculo',ascending = False, inplace = True)
df_furto_cel_bel_dp

   cisp  roubo_veiculo
0    54          24945

## Isin dicionario e Ano específico

In [44]:
munic_pedido = ['Belford Roxo', 'Nova Iguaçu', 'Queimados']
df_br_ni_qm = df.loc[(df['munic'].isin(munic_pedido)) & (df['ano'] == 2025)] #cada condição no seu parenteses
df_br_ni_qm                                                                  #se atentar a chave do loc

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
35577,52,1,2025,2025m01,20,3,Nova Iguaçu,3303500,Baixada Fluminense,9,...,9.0,0.0,101,6,0,0,0,0,1257,3
35579,54,1,2025,2025m01,39,3,Belford Roxo,3300456,Baixada Fluminense,15,...,28.0,4.0,143,16,1,0,0,0,1561,3
35580,55,1,2025,2025m01,24,3,Queimados,3304144,Baixada Fluminense,1,...,7.0,4.0,64,1,0,0,0,0,521,3
35581,56,1,2025,2025m01,20,3,Nova Iguaçu,3303500,Baixada Fluminense,11,...,11.0,0.0,96,10,1,0,0,0,705,3
35583,58,1,2025,2025m01,20,3,Nova Iguaçu,3303500,Baixada Fluminense,8,...,7.0,0.0,146,11,2,0,0,0,1187,3
35714,52,2,2025,2025m02,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,20.0,1.0,81,7,0,0,0,0,1123,3
35716,54,2,2025,2025m02,39,3,Belford Roxo,3300456,Baixada Fluminense,4,...,16.0,1.0,126,14,2,0,0,0,1404,3
35717,55,2,2025,2025m02,24,3,Queimados,3304144,Baixada Fluminense,3,...,11.0,0.0,67,4,0,0,0,0,479,3
35718,56,2,2025,2025m02,20,3,Nova Iguaçu,3303500,Baixada Fluminense,7,...,7.0,0.0,107,15,0,0,0,0,768,3
35720,58,2,2025,2025m02,20,3,Nova Iguaçu,3303500,Baixada Fluminense,14,...,15.0,1.0,144,14,0,0,0,0,1071,3
35851,52,3,2025,2025m03,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,15.0,2.0,84,5,0,0,0,0,1156,3
35853,54,3,2025,2025m03,39,3,Belford Roxo,3300456,Baixada Fluminense,10,...,23.0,2.0,180,24,2,0,0,0,1411,3
35854,55,3,2025,2025m03,24,3,Queimados,3304144,Baixada Fluminense,1,...,9.0,0.0,52,5,2,0,0,0,519,3
35855,56,3,2025,2025m03,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,9.0,2.0,93,10,5,0,0,0,767,3
35857,58,3,2025,2025m03,20,3,Nova Iguaçu,3303500,Baixada Fluminense,15,...,14.0,1.0,143,23,0,0,0,0,1239,3
35988,52,4,2025,2025m04,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,13.0,1.0,68,5,0,0,0,0,1154,3
35990,54,4,2025,2025m04,39,3,Belford Roxo,3300456,Baixada Fluminense,7,...,12.0,3.0,117,20,1,0,0,0,1258,3
35991,55,4,2025,2025m04,24,3,Queimados,3304144,Baixada Fluminense,2,...,7.0,0.0,64,3,0,1,0,0,467,3
35992,56,4,2025,2025m04,20,3,Nova Iguaçu,3303500,Baixada Fluminense,7,...,8.0,1.0,82,14,0,0,0,0,725,3
35994,58,4,2025,2025m04,20,3,Nova Iguaçu,3303500,Baixada Fluminense,7,...,11.0,0.0,130,13,0,0,0,0,1115,3
36125,52,5,2025,2025m05,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,15.0,2.0,68,3,0,0,0,0,1177,3
36127,54,5,2025,2025m05,39,3,Belford Roxo,3300456,Baixada Fluminense,13,...,35.0,3.0,99,14,2,0,0,0,1366,3
36128,55,5,2025,2025m05,24,3,Queimados,3304144,Baixada Fluminense,1,...,9.0,4.0,68,3,0,0,0,0,480,3
36129,56,5,2025,2025m05,20,3,Nova Iguaçu,3303500,Baixada Fluminense,9,...,13.0,2.0,88,15,1,0,0,0,794,3
36131,58,5,2025,2025m05,20,3,Nova Iguaçu,3303500,Baixada Fluminense,18,...,12.0,2.0,137,17,1,0,0,0,1252,3
36262,52,6,2025,2025m06,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,15.0,3.0,57,4,0,0,0,0,1049,3
36264,54,6,2025,2025m06,39,3,Belford Roxo,3300456,Baixada Fluminense,5,...,20.0,0.0,113,16,1,0,0,0,1355,3
36265,55,6,2025,2025m06,24,3,Queimados,3304144,Baixada Fluminense,1,...,3.0,0.0,59,4,1,0,0,0,486,3
36266,56,6,2025,2025m06,20,3,Nova Iguaçu,3303500,Baixada Fluminense,3,...,5.0,0.0,87,10,0,0,0,0,703,3
36268,58,6,2025,2025m06,20,3,Nova Iguaçu,3303500,Baixada Fluminense,18,...,6.0,1.0,123,13,3,0,0,0,1163,3
36399,52,7,2025,2025m07,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,19.0,1.0,65,9,1,0,0,0,1226,3
36401,54,7,2025,2025m07,39,3,Belford Roxo,3300456,Baixada Fluminense,5,...,33.0,1.0,102,20,1,0,0,0,1376,3
36402,55,7,2025,2025m07,24,3,Queimados,3304144,Baixada Fluminense,1,...,10.0,0.0,51,15,1,0,0,0,558,3
36403,56,7,2025,2025m07,20,3,Nova Iguaçu,3303500,Baixada Fluminense,4,...,7.0,0.0,104,10,0,0,0,0,851,3
36405,58,7,2025,2025m07,20,3,Nova Iguaçu,3303500,Baixada Fluminense,10,...,14.0,1.0,144,14,1,0,0,0,1298,3
36536,52,8,2025,2025m08,20,3,Nova Iguaçu,3303500,Baixada Fluminense,1,...,12.0,0.0,62,10,2,0,0,0,1181,3
36538,54,8,2025,2025m08,39,3,Belford Roxo,3300456,Baixada Fluminense,5,...,31.0,1.0,119,14,0,0,0,0,1320,3
36539,55,8,2025,2025m08,24,3,Queimados,3304144,Baixada Fluminense,3,...,15.0,0.0,42,9,1,0,0,0,473,3
36540,56,8,2025,2025m08,20,3,Nova Iguaçu,3303500,Baixada Fluminense,7,...,9.0,1.0,97,10,1,0,0,0,746,3
36542,58,8,2025,2025m08,20,3,Nova Iguaçu,3303500,Baixada Fluminense,8,...,14.0,0.0,139,8,0,0,0,0,1242,3
36673,52,9,2025,2025m09,20,3,Nova Iguaçu,3303500,Baixada Fluminense,0,...,21.0,0.0,105,11,1,0,0,0,1236,3
36675,54,9,2025,2025m09,39,3,Belford Roxo,3300456,Baixada Fluminense,8,...,31.0,0.0,169,8,0,0,0,0,1453,3
36676,55,9,2025,2025m09,24,3,Queimados,3304144,Baixada Fluminense,2,...,14.0,0.0,63,6,0,0,0,0,528,3
36677,56,9,2025,2025m09,20,3,Nova Iguaçu,3303500,Baixada Fluminense,9,...,14.0,1.0,104,8,0,0,0,0,794,3
36679,58,9,2025,2025m09,20,3,Nova Iguaçu,3303500,Baixada Fluminense,6,...,18.0,0.0,150,16,1,0,0,0,1260,3
36810,52,10,2025,2025m10,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,16.0,0.0,84,8,2,0,0,0,1237,3
36812,54,10,2025,2025m10,39,3,Belford Roxo,3300456,Baixada Fluminense,12,...,24.0,2.0,140,22,0,0,0,0,1396,3
36813,55,10,2025,2025m10,24,3,Queimados,3304144,Baixada Fluminense,1,...,8.0,1.0,59,9,0,0,0,0,507,3
36814,56,10,2025,2025m10,20,3,Nova Iguaçu,3303500,Baixada Fluminense,7,...,7.0,0.0,103,11,0,0,0,0,801,3
36816,58,10,2025,2025m10,20,3,Nova Iguaçu,3303500,Baixada Fluminense,6,...,14.0,0.0,139,16,0,0,0,0,1238,3
36947,52,11,2025,2025m11,20,3,Nova Iguaçu,3303500,Baixada Fluminense,0,...,24.0,2.0,63,14,0,0,0,0,1154,3
36949,54,11,2025,2025m11,39,3,Belford Roxo,3300456,Baixada Fluminense,12,...,24.0,3.0,127,17,2,0,0,0,1219,3
36950,55,11,2025,2025m11,24,3,Queimados,3304144,Baixada Fluminense,0,...,3.0,1.0,43,4,0,0,0,0,439,3
36951,56,11,2025,2025m11,20,3,Nova Iguaçu,3303500,Baixada Fluminense,5,...,2.0,0.0,87,10,0,0,0,0,676,3
36953,58,11,2025,2025m11,20,3,Nova Iguaçu,3303500,Baixada Fluminense,12,...,12.0,1.0,152,8,2,0,0,0,1201,3
37084,52,12,2025,2025m12,20,3,Nova Iguaçu,3303500,Baixada Fluminense,2,...,10.0,0.0,102,13,0,0,0,0,1248,3
37086,54,12,2025,2025m12,39,3,Belford Roxo,3300456,Baixada Fluminense,19,...,11.0,0.0,131,21,2,0,1,0,1114,3
37087,55,12,2025,2025m12,24,3,Queimados,3304144,Baixada Fluminense,2,...,3.0,0.0,50,5,0,0,0,0,435,3
37088,56,12,2025,2025m12,20,3,Nova Iguaçu,3303500,Baixada Fluminense,3,...,7.0,0.0,111,10,1,0,0,0,711,3
37090,58,12,2025,2025m12,20,3,Nova Iguaçu,3303500,Baixada Fluminense,7,...,6.0,0.0,154,14,0,0,0,0,1272,3

## Array e Numpy - calculos e estatísticas

In [46]:
array_furto_cel_dp = np.array(df_furto_cel_dp['furto_celular'])
array_furto_cel_dp

array([26111, 25440, 18822, 17537, 16127, 15278, 14773, 14436, 14247,
       12833, 12231,  8899,  8849,  8701,  8342,  8223,  8132,  7804,
        7360,  7261,  7040,  6971,  6669,  6617,  6185,  5770,  5655,
        5596,  5458,  5357,  5041,  4979,  4758,  4755,  4708,  4652,
        4162,  4126,  4120,  4052,  3885,  3795,  3779,  3762,  3531,
        3421,  3376,  3286,  3142,  2997,  2968,  2869,  2707,  2681,
        2611,  2416,  2393,  2353,  2322,  2207,  2158,  2150,  2139,
        2132,  2089,  1836,  1836,  1825,  1744,  1714,  1663,  1630,
        1546,  1485,  1473,  1441,  1390,  1376,  1309,  1250,  1149,
        1096,  1050,  1042,  1035,   907,   836,   822,   810,   752,
         743,   662,   654,   633,   632,   626,   583,   565,   516,
         513,   506,   499,   461,   453,   451,   442,   410,   405,
         385,   374,   369,   362,   357,   304,   302,   260,   244,
         238,   213,   206,   203,   197,   172,   167,   155,   147,
         129,   124,   116,   111,    90,    83,    73,    73,    65,
          56,    55,    47])

In [51]:
media = np.mean(array_furto_cel_dp)
mediana = np.median(array_furto_cel_dp)

In [53]:
print(f'Média {media:.2f}\n Mediana {mediana}')

Média 3534.01
 Mediana 1729.0

## Quartis 100/4 partes de 25%

In [55]:
media = np.mean(array_furto_cel_dp)
mediana = np.median(array_furto_cel_dp)
q1 = np.percentile(array_furto_cel_dp, 25)
q2 = np.percentile(array_furto_cel_dp,50)
q3 = np.percentile(array_furto_cel_dp,75)

In [57]:
print(f'Média {media:.2f}')
print(f'Mediana {mediana}')
print(f'Q1: {q1}')
print(f'Q2: {q2}')
print(f'Q3: {q3}')

Média 3534.01
Mediana 1729.0
Q1: 455.0
Q2: 1729.0
Q3: 4694.0

In [59]:
df_furto_cel_acima_q3 = df_furto_cel_dp.loc[df_furto_cel_dp['furto_celular'] > q3]
df_furto_cel_acima_q3

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
5       9          15278
6      10          14773
14     18          14436
1       4          14247
28     32          12833
31     35          12231
15     19           8899
52     59           8849
13     17           8701
67     76           8342
25     29           8223
38     42           8132
9      13           7804
19     23           7360
11     15           7261
17     21           7040
30     34           6971
33     37           6669
3       6           6617
29     33           6185
18     22           5770
45     52           5655
32     36           5596
37     41           5458
16     20           5357
68     77           5041
104   126           4979
20     24           4758
65     74           4755
23     27           4708

## Exercício 1

In [84]:
df_roubo_veic = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veic.sort_values(by = 'roubo_veiculo', ascending = False, inplace = True)
df_roubo_veic

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [85]:
array_roubo_veic = np.array(df_roubo_veic['roubo_veiculo'])
array_roubo_veic

array([37780, 32839, 29663, 27920, 27543, 24945, 20696, 20044, 19790,
       19422, 19403, 18414, 18069, 16895, 16351, 15653, 15193, 15122,
       14912, 14212, 14000, 12866, 12516, 12108, 12019, 11076, 11057,
       10803, 10165,  9279,  9124,  8694,  8571,  8567,  8203,  7861,
        7739,  7376,  7353,  6929,  6475,  5922,  5235,  4697,  4669,
        4137,  4051,  3888,  3727,  3349,  3271,  2983,  2954,  2781,
        2769,  2538,  2219,  2135,  2057,  2027,  1958,  1957,  1949,
        1922,  1500,  1372,  1316,  1286,  1266,  1188,  1060,  1033,
         972,   934,   790,   776,   759,   659,   582,   502,   481,
         448,   441,   407,   345,   335,   322,   316,   314,   313,
         313,   286,   270,   269,   244,   204,   190,   185,   174,
         174,   152,   130,   106,   103,    92,    91,    87,    80,
          67,    66,    65,    60,    58,    49,    48,    47,    44,
          43,    39,    29,    27,    27,    24,    23,    21,    21,
          21,    20,    20,    18,    17,    13,     9,     8,     8,
           7,     6,     2])

In [86]:
media = np.mean(array_roubo_veic)
mediana = np.median(array_roubo_veic)
q1 = np.percentile(array_roubo_veic,25)
q2 = np.percentile(array_roubo_veic,50) 
q3 = np.percentile(array_roubo_veic,75)

In [87]:
print(f'Média: {media:.2f}')
print(f'Mediana: {mediana}')
print(f'Q1: {q1}')
print(f'Q2: {q2}')
print(f'Q3: {q3}')

Média: 5250.84
Mediana: 1227.0
Q1: 103.75
Q2: 1227.0
Q3: 8117.5

In [88]:
roubo_veic_acima_q3 = df_roubo_veic.loc[df_roubo_veic['roubo_veiculo'] > q3]
roubo_veic_acima_q3

    cisp  roubo_veiculo
52    59          37780
57    64          32839
35    39          29663
23    27          27920
30    34          27543
47    54          24945
53    60          20696
34    38          20044
17    21          19790
31    35          19422
36    40          19403
65    74          18414
29    33          18069
25    29          16895
51    58          16351
45    52          15653
18    22          15193
27    31          15122
40    44          14912
63    72          14212
64    73          14000
26    30          12866
50    57          12516
20    24          12108
49    56          12019
21    25          11076
24    28          11057
19    23          10803
66    75          10165
55    62           9279
16    20           9124
28    32           8694
69    78           8571
46    53           8567
62    71           8203

## Média confiável - distancia

In [93]:
distancia = (media - mediana)/mediana
print(f'Média precisa: {distancia:.2%}')

Média precisa: 327.94%

## Atividade 3

In [101]:
df_aaapai_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_dp.sort_values(by = 'aaapai',ascending = False, inplace = True)
df_aaapai_dp

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [102]:
array_aaapai_dp = np.array(df_aaapai_dp['aaapai'])
array_aaapai_dp

array([3713., 3657., 3365., 3349., 3218., 3030., 2858., 2842., 2749.,
       2702., 2696., 2297., 2271., 2260., 2140., 2085., 2058., 2043.,
       1894., 1815., 1812., 1798., 1748., 1675., 1653., 1647., 1637.,
       1612., 1553., 1546., 1546., 1405., 1362., 1360., 1277., 1272.,
       1242., 1236., 1216., 1187., 1184., 1140., 1133., 1128., 1112.,
       1081., 1049., 1015.,  983.,  982.,  939.,  891.,  885.,  882.,
        877.,  830.,  818.,  803.,  802.,  799.,  787.,  778.,  775.,
        752.,  744.,  742.,  703.,  702.,  690.,  683.,  636.,  631.,
        610.,  599.,  589.,  558.,  536.,  518.,  505.,  408.,  395.,
        391.,  387.,  386.,  352.,  347.,  329.,  326.,  323.,  320.,
        318.,  318.,  313.,  311.,  311.,  301.,  288.,  287.,  287.,
        283.,  277.,  273.,  231.,  221.,  204.,  189.,  174.,  170.,
        163.,  161.,  154.,  140.,  114.,  112.,   95.,   93.,   89.,
         87.,   86.,   75.,   68.,   66.,   63.,   63.,   62.,   45.,
         45.,   44.,   39.,   36.,   33.,   28.,   27.,   19.,   16.,
         14.,   13.,   12.])

In [103]:
media = np.mean(array_aaapai_dp)
mediana = np.median(array_aaapai_dp)

In [104]:
print(f'Média: {media:.2f}')
print(f'Mediana: {mediana}')

Média: 909.27
Mediana: 686.5

In [105]:
distancia = (media-mediana)/ mediana
print(f'Margem de erro: {distancia:.2%}')

Margem de erro: 32.45%