In [4]:
import pandas as pd

In [28]:
import numpy as np

In [7]:
df = pd.read_csv('pedidos_narashop.csv',sep = ';')
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3
...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18

In [15]:
df['valor_total'] = df['quantidade'] * df['valor_unitario']
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_total
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4,87.67
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18,197.10

In [17]:
df_categoria_fat = df.groupby('categoria')['valor_total'].sum().reset_index()
df_categoria_fat = df_categoria_fat.sort_values(by='valor_total',ascending = False)
df_categoria_fat

          categoria  valor_total
2       Eletrônicos  37037997.65
3          Esportes   8058234.35
1  Casa e Decoração   3333395.06
0        Brinquedos   2306126.65

In [25]:
df_entregue_500 = df.loc[(df['status_pedido'] == 'Entregue') & (df['valor_total'] >= 500)]
df_entregue_500

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_total
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
19,10020,Renato Cavalcante,Eletrônicos,Smartwatch,Entregue,3,461.46,3,1384.38
25,10026,Larissa Nunes,Brinquedos,Telescópio Infantil,Entregue,5,487.03,2,2435.15
...,...,...,...,...,...,...,...,...,...
19987,29988,Sérgio Machado,Casa e Decoração,Fritadeira Air Fryer,Entregue,5,403.51,8,2017.55
19989,29990,Diego Fernandes,Esportes,Bicicleta Ergométrica,Entregue,1,1235.61,10,1235.61
19992,29993,Larissa Nunes,Casa e Decoração,Tapete Sala,Entregue,3,279.57,18,838.71
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36

In [26]:
df_produto_valor_vendido = df.groupby('produto')['valor_total'].sum().reset_index().sort_values(by = 'valor_total', ascending = False)

df_produto_valor_vendido.head()

                  produto  valor_total
27               Notebook  15091721.74
37               Smart TV   8474171.95
38             Smartphone   6806241.19
1   Bicicleta Ergométrica   5949159.26
40                 Tablet   3258725.63

In [30]:
array_produto_val_total = np.array(df_produto_valor_vendido['valor_total'])
array_produto_val_total

array([15091721.74,  8474171.95,  6806241.19,  5949159.26,  3258725.63,
        1344856.8 ,   980636.15,   760544.58,   719921.59,   696912.4 ,
         409588.1 ,   372827.72,   365791.62,   362150.99,   340633.78,
         287378.44,   278877.33,   277410.42,   276184.73,   271850.88,
         264729.81,   264563.7 ,   259327.03,   233110.8 ,   224794.69,
         200280.49,   200234.01,   196385.59,   195027.74,   192107.97,
         189885.38,    93768.2 ,    83236.49,    77586.08,    74555.56,
          74070.26,    73266.61,    70889.32,    64156.  ,    63532.51,
          57532.21,    51701.41,    51088.67,    50209.91,    36586.33,
          26224.38,    23767.2 ,    17550.06])

In [32]:
q1 = np.percentile(array_produto_val_total,25)
q3 = np.percentile(array_produto_val_total,75)

In [35]:
df_25_mais = df_produto_valor_vendido.loc[df_produto_valor_vendido ['valor_total'] > q3]
df_25_mais

                  produto  valor_total
27               Notebook  15091721.74
37               Smart TV   8474171.95
38             Smartphone   6806241.19
1   Bicicleta Ergométrica   5949159.26
40                 Tablet   3258725.63
39             Smartwatch   1344856.80
13   Fritadeira Air Fryer    980636.15
17        Jogo de Panelas    760544.58
36            SSD Externo    719921.59
45       Tênis de Corrida    696912.40
44    Telescópio Infantil    409588.10
43       Teclado Mecânico    372827.72

In [36]:
df_25_menos = df_produto_valor_vendido.loc[df_produto_valor_vendido['valor_total']< q1 ]
df_25_menos

                     produto  valor_total
0          Bermuda Esportiva     73266.61
8        Conjunto de Toalhas     70889.32
6        Carregador Portátil     64156.00
14           Garrafa Térmica     63532.51
10         Difusor de Aromas     57532.21
34  Quebra-Cabeça 1000 peças     51701.41
30                   Pelúcia     51088.67
42            Tapete de Yoga     50209.91
28    Organizador de Gavetas     36586.33
32            Porta-Retratos     26224.38
9             Corda de Pular     23767.20
24       Massinha de Modelar     17550.06

In [37]:
df_fat_vendedor  = df.groupby('vendedor')['valor_total'].sum().reset_index().sort_values(by = 'valor_total', ascending = False)
df_fat_vendedor

             vendedor  valor_total
3            Ana Lima   3950687.71
35    Rafael Oliveira   3934561.13
23    Juliana Martins   3226272.18
12    Diego Fernandes   3180786.47
8        Carlos Souza   3065164.09
32     Patrícia Rocha   3008726.29
6         Bruno Alves   2894957.47
17     Fernanda Costa   2855540.29
46      Vanessa Sousa   1118480.12
13      Débora Vieira   1061689.40
7      Camila Pereira   1046413.86
18     Flávia Azevedo   1035353.05
43      Tatiane Cunha    975057.20
34  Priscila Teixeira    969315.18
44      Thiago Santos    936837.28
2        Amanda Silva    900957.64
28   Marcelo Monteiro    884924.36
31    Natália Barbosa    878844.60
24      Larissa Nunes    873830.90
25       Leandro Reis    824988.84
5     Bianca Carvalho    822331.10
33   Paulo Nascimento    801924.38
1      Aline Ferreira    733366.10
39    Rodrigo Batista    732576.76
4       Anderson Cruz    714554.83
9       Claudia Ramos    706470.26
41      Simone Castro    664679.66
49     Willian Duarte    656240.17
42     Sérgio Machado    643342.60
26    Letícia Moreira    581852.56
40       Sabrina Melo    575799.70
38    Roberto Cardoso    480599.38
37  Renato Cavalcante    470882.91
21      Henrique Dias    462361.32
20      Gustavo Pinto    461151.06
27      Lucas Ribeiro    453701.57
16       Felipe Gomes    387956.88
19       Fábio Araújo    373244.59
29    Mariana Correia    363231.71
22     Isabela Mendes    347744.74
48     Vinícius Lopes    327272.71
14    Eduardo Freitas    291632.72
10  Cristiane Tavares    206953.21
11      Danilo Campos    163822.10
30     Matheus Borges    154941.79
45        Tiago Moura    142846.86
15  Elaine Figueiredo    127838.65
47       Vera Andrade    115512.99
36     Raquel Esteves     85104.85
0   Alexandre Lacerda     62427.49

In [39]:
array_vendedor = np.array(df_fat_vendedor['valor_total'])
array_vendedor

array([3950687.71, 3934561.13, 3226272.18, 3180786.47, 3065164.09,
       3008726.29, 2894957.47, 2855540.29, 1118480.12, 1061689.4 ,
       1046413.86, 1035353.05,  975057.2 ,  969315.18,  936837.28,
        900957.64,  884924.36,  878844.6 ,  873830.9 ,  824988.84,
        822331.1 ,  801924.38,  733366.1 ,  732576.76,  714554.83,
        706470.26,  664679.66,  656240.17,  643342.6 ,  581852.56,
        575799.7 ,  480599.38,  470882.91,  462361.32,  461151.06,
        453701.57,  387956.88,  373244.59,  363231.71,  347744.74,
        327272.71,  291632.72,  206953.21,  163822.1 ,  154941.79,
        142846.86,  127838.65,  115512.99,   85104.85,   62427.49])

In [ ]:
q1 = np.percentile(array_vendedor,25)
q3 = np.percentile(array_vendedor,75)

In [42]:
print(f'Q1: {q1}')
print(f'Q3: {q3}')

Q1: 73869.3475
Q3: 367550.645

In [40]:
df_vendedor_mais = df_fat_vendedor.loc[df_fat_vendedor['valor_total'] > q3]
df_vendedor_mais

             vendedor  valor_total
3            Ana Lima   3950687.71
35    Rafael Oliveira   3934561.13
23    Juliana Martins   3226272.18
12    Diego Fernandes   3180786.47
8        Carlos Souza   3065164.09
32     Patrícia Rocha   3008726.29
6         Bruno Alves   2894957.47
17     Fernanda Costa   2855540.29
46      Vanessa Sousa   1118480.12
13      Débora Vieira   1061689.40
7      Camila Pereira   1046413.86
18     Flávia Azevedo   1035353.05
43      Tatiane Cunha    975057.20
34  Priscila Teixeira    969315.18
44      Thiago Santos    936837.28
2        Amanda Silva    900957.64
28   Marcelo Monteiro    884924.36
31    Natália Barbosa    878844.60
24      Larissa Nunes    873830.90
25       Leandro Reis    824988.84
5     Bianca Carvalho    822331.10
33   Paulo Nascimento    801924.38
1      Aline Ferreira    733366.10
39    Rodrigo Batista    732576.76
4       Anderson Cruz    714554.83
9       Claudia Ramos    706470.26
41      Simone Castro    664679.66
49     Willian Duarte    656240.17
42     Sérgio Machado    643342.60
26    Letícia Moreira    581852.56
40       Sabrina Melo    575799.70
38    Roberto Cardoso    480599.38
37  Renato Cavalcante    470882.91
21      Henrique Dias    462361.32
20      Gustavo Pinto    461151.06
27      Lucas Ribeiro    453701.57
16       Felipe Gomes    387956.88
19       Fábio Araújo    373244.59

In [41]:
df_vendedor_menos = df_fat_vendedor.loc[df_fat_vendedor['valor_total'] < q1]
df_vendedor_menos

            vendedor  valor_total
0  Alexandre Lacerda     62427.49

In [45]:
array_med_total = np.array(df['valor_total'])
array_med_total

array([  490.05,  2399.56, 18874.8 , ...,  7888.25,   578.36,   197.1 ],
      shape=(20000,))

In [48]:
media = np.mean(array_med_total)
mediana = np.median(array_med_total)
distancia = (media - mediana)/mediana

In [52]:
print(f'Média: {media:.2f}')
print(f'Mediana: {mediana}')
print(f'Média confiável: {distancia:.2f}%')

Média: 2536.79
Mediana: 882.635
Média confiável: 1.87%